### PR TITLE
Make recipe dir name the same as package name

### PR DESCRIPTION
**Pull request by rendinam**
Hyphen -> underscore

### CODE REVIEW

**Comment by pllim** [comment]
The hyphen was used on purpose. See https://pypi.python.org/pypi/spherical-geometry . If we don't use hyphen, someone installed `spherical-geometry` from `pip` but then want the version in AstroConda won't find `spherical-geometry` using `conda install` command. Then we have to explain to them that somehow it is underscore in our channel. Confused yet?

**Comment by pllim** [comment]
I recommend you revert this PR.

**Comment by rendinam** [comment]
I am interested in making the recipe directory name, internal metadata name, and repository name self consistent, because having those values differ is likely to cause problems. Can that be done here by renaming everything to 'spherical-geometry', including the repository spacetelescope/sperical_geometry?

**Comment by pllim** [comment]
What kind of problem? I just renamed repository name from "sphere" to "spherical_geometry" a few days ago. I chose to have the repository name to be the same as package import name, as that was less confusing to me, but there are no rules against renaming it again. If you rename it again, you also have to rename it in several other places, see all the linked PRs on spacetelescope/spherical_geometry#104. I don't have time to do this again.

**Comment by rendinam** [comment]
The `name` field in the meta.yaml file is what determines the name of the package that conda generates, not the recipe directory name, which is what was changed here. Bookkeeping in the build system becomes more difficult if the names of the directory, and name metadata are not the same, which is the reasoning behind this change. As it stands, this recipe will still generate a package named `spherical_geometry`.

**Comment by pllim** [comment]
Then is there a way to make the conda channel make the package named `spherical-geometry`? Also, your changes (whatever the final decision is) need to be consistent with `contrib`.

**Comment by rendinam** [comment]
It disturbs the balance of the universe, but yes.
I will revert this name change, restoring `spherical-geometry` as the recipe name, have the recipe reference the `spacetelescope/spherical_geometry` repository, and change the name of the produced package to `spherical-geometry`.
Once this is complete and tested, I will propagate equivalent changes to the contrib recipe, as initially planned. Thanks for explaining the situation.

**Comment by pllim** [comment]
Thanks! Disturbing the universe is what I do...

**Pull request merged**
