### PR TITLE
Add wss_tools

### PR DESCRIPTION
**Pull request by rendinam**

### CODE REVIEW

**Comment by pllim** [comment]
Please don't. The reason I did not add it here is because TEL does not want me to. So unless you got a blessing from Matt Lallo et al., don't do it.

**Comment by rendinam** [comment]
I see that the documentation for wss_tools mentions the decision to not include in astroconda. In communication with @jhunkeler and @stsci-hack, however, it was determined to add this package as part of a solution to resolve installation issues as per footprints ticket #109415.

**Comment by pllim** [comment]
Did you get approval from TEL to do so?

**Comment by rendinam** [comment]
It's certainly possible that there are other considerations of which we are not aware.
I have not seen any explicit TEL approval.  Who has oversight on this decision?

**Comment by jhunkeler** [comment]
@pllim I'll confirm with TEL. There didn't seem to be any opposition to doing this when we mentioned it about four times in the email thread.

**Comment by jhunkeler** [comment]
@rendinam contacted TEL and they don't want it. I'm closing PR so we don't accidentally merge it.

**Pull request closed without merging**
