### PR TITLE
Initial commit; astroquery

### PR DESCRIPTION
**Pull request by jhunkeler**
Requires #56 #57 #58

### CODE REVIEW

**Comment by pllim** [comment]
Huh... the requirements are not the ones I remember being listed in `astroquery` doc. ❓

**Comment by pllim** [comment]
Ref: http://astroquery.readthedocs.io/en/latest/#requirements

**Comment by jhunkeler** [comment]
Ref: https://pypi.python.org/pypi/keyring#id

The `keyring` dependency requires FreeDesktop's `Secret Service` when imported under Linux. Also, `secretservice` requires extremely deprecated packages (`dbus-python` and `dbus-glib`). 

Are there not better ways available to do this? 😢 


## Build log failure breakdown
```Installed /srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/astroquery-0.3.5-py2.7.egg
Processing dependencies for astroquery==0.3.5
Searching for secretstorage
```
```python
Traceback (most recent call last):
  File "setup.py", line 130, in <module>
    **package_info
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/install.py", line 67, in run
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/install.py", line 117, in do_egg_install
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 409, in run
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 645, in easy_install
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 696, in install_item
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 741, in process_distribution
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 851, in resolve
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1123, in best_match
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1135, in obtain
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 652, in easy_install
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/package_index.py", line 634, in fetch_distribution
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/package_index.py", line 469, in find_packages
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/package_index.py", line 807, in scan_url
  File "/srv/iraf/bldtmp/p0KF/p/conda-bld/astroquery_1502697675168/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/package_index.py", line 307, in process_url
```
```python
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/secretstorage/r
```

**Comment by pllim** [comment]
@jhunkeler , if you think the `keyring` dependency should be changed, please open an issue over at https://github.com/astropy/astroquery/issues (xref astropy/astroquery#396). Thank you for the clarifications!

**Pull request merged**
